version: "3"
services: 
  frontend: 
    build:
      context: .
      dockerfile: Dockerfile
    tty: true 
    ports:
      - 3000:3000
    networks:
      - makuhari_city
networks:
  makuhari_city:
    external: true
